//
//  PokeDexViewController.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 1/04/25.
//  Template generated by Nishi
//

import UIKit
import Lottie

class PokeDexViewController: UIViewController {
    var presenter: PokeDexPresenterProtocol?
    let mainView = PokeDexView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view = mainView
        presenter?.viewDidLoad()
    }
}

extension PokeDexViewController: PokeDexViewProtocol {
    func playBackgroundAnimation() {
        DispatchQueue.main.async {
            self.mainView.animationView.animation = LottieAnimation.named(AppLocalized.AnimationBackgroundPokedex)
            self.mainView.animationView.play()
        }
    }
}
