//
//  PokeDexView+Layout.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 1/04/25.
//  Template generated by Nishi
//

import UIKit

extension PokeDexView {
    func addViews() {
        addSubview(animationView)
        animationView.translatesAutoresizingMaskIntoConstraints = false
    }
    
    func setupConstraints() {
        NSLayoutConstraint.activate([
            animationView.topAnchor.constraint(equalTo: topAnchor),
            animationView.leadingAnchor.constraint(equalTo: leadingAnchor),
            animationView.trailingAnchor.constraint(equalTo: trailingAnchor),
            animationView.bottomAnchor.constraint(equalTo: bottomAnchor)
        ])
    }
}
