//
//  PokeDexProtocols.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 1/04/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Nishi
//

// PokeDexProtocols.swift

import Foundation

//MARK: Presenter -> Router
protocol PokeDexWireframeProtocol: AnyObject {
    // Agrega métodos de navegación si es necesario
    // func navigateToPokemonDetail(with pokemon: Pokemon)
}

//MARK: View -> Presenter
protocol PokeDexPresenterProtocol: AnyObject {
    var interactor: PokeDexInteractorInputProtocol? { get set }
    
    func viewDidLoad()
    func searchDidBegin()
    func cancelSearch()
    func searchPokemon(with text: String)
    func didSelectPokemon(at index: Int)
    func getService()
    var numberOfPokemons: Int { get }
    func pokemon(at index: Int) -> ResultPokeDex?
}

//MARK: Interactor -> Presenter
protocol PokeDexInteractorOutputProtocol: AnyObject {
    // Agrega métodos para recibir datos del interactor
    // func didReceivePokemons(_ pokemons: [Pokemon])
    // func didFailToLoadPokemons(with error: Error)
}

//MARK: Presenter -> Interactor
protocol PokeDexInteractorInputProtocol: AnyObject {
    var presenter: PokeDexInteractorOutputProtocol? { get set }
    
    func fetchServiceListPokeDex(completion: @escaping (Result<ListPokedexResponse, Error>) -> Void)
}

//MARK: Presenter -> View
protocol PokeDexViewProtocol: AnyObject {
    var presenter: PokeDexPresenterProtocol? { get set }
    
    func playBackgroundAnimation()
    func reloadCollectionView()
    func showCancelButton(_ show: Bool)
    
    func setPokeDexData(_ data: [ResultPokeDex])

}
