//
//  PokeDexProtocols.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 1/04/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Nishi
//

import Foundation

//MARK: Presenter -> Router
protocol PokeDexWireframeProtocol: AnyObject {
    
}

//MARK: View -> Presenter
protocol PokeDexPresenterProtocol: AnyObject {
    var interactor: PokeDexInteractorInputProtocol? { get set }
    
    func viewDidLoad()
}

//MARK: Interactor -> Presenter
protocol PokeDexInteractorOutputProtocol: AnyObject {
    
}

//MARK: Presenter -> Interactor
protocol PokeDexInteractorInputProtocol: AnyObject {
    var presenter: PokeDexInteractorOutputProtocol?  { get set }
}

//MARK: Presenter -> View
protocol PokeDexViewProtocol: AnyObject {
    var presenter: PokeDexPresenterProtocol?  { get set }
    
    func playBackgroundAnimation()
}
