//
//  PokeDexInteractor.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 1/04/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Nishi
//

import UIKit

class PokeDexInteractor: PokeDexInteractorInputProtocol {
    weak var presenter: PokeDexInteractorOutputProtocol?
}
