//
//  PokeDexInteractor.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 1/04/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Nishi
//

import UIKit

class PokeDexInteractor: PokeDexInteractorInputProtocol {
    var presenter: (any PokeDexInteractorOutputProtocol)?
    
    let pokeManager = PokeManager.shared
    
    func fetchAllPokemons(completion: @escaping (Result<[ResultPokeDex], Error>) -> Void) {
        let parameters = ["limit": "151", "offset": "0"]
        
        pokeManager.getData(endpoint: .listPokedex, parameters: parameters) {
            (result: Result<ListPokedexResponse, Error>) in
            switch result {
            case .success(let response):
                completion(.success(response.results ?? []))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
}
