//
//  PokeDexView+Layout.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 1/04/25.
//  Template generated by Nishi
//

import UIKit

extension PokeDexView {
    func addViews() {
        searchStackView.axis = .horizontal
        searchStackView.distribution = .equalSpacing
        searchStackView.alignment = .center
        searchStackView.spacing = 0
        searchStackView.translatesAutoresizingMaskIntoConstraints = false
        searchBar.translatesAutoresizingMaskIntoConstraints = false
        cancelButton.translatesAutoresizingMaskIntoConstraints = false
        searchStackView.addArrangedSubview(searchBar)
        searchStackView.addArrangedSubview(cancelButton)
        addSubview(animationView)
        addSubview(searchStackView)
        addSubview(headerImageView)
        addSubview(collectionView)
    }
    
    func setupConstraints() {
        NSLayoutConstraint.activate([
            animationView.topAnchor.constraint(equalTo: topAnchor),
            animationView.leadingAnchor.constraint(equalTo: leadingAnchor),
            animationView.trailingAnchor.constraint(equalTo: trailingAnchor),
            animationView.bottomAnchor.constraint(equalTo: bottomAnchor),
            
            searchStackView.topAnchor.constraint(equalTo: safeAreaLayoutGuide.topAnchor, constant: 8),
            searchStackView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 20),
            searchStackView.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -20),
            searchStackView.heightAnchor.constraint(equalToConstant: 44),
            
            searchBar.heightAnchor.constraint(equalToConstant: 44),
            headerImageView.topAnchor.constraint(equalTo: searchStackView.bottomAnchor, constant: 16),
            headerImageView.centerXAnchor.constraint(equalTo: centerXAnchor),
            headerImageView.heightAnchor.constraint(equalToConstant: 120),
            headerImageView.widthAnchor.constraint(equalTo: widthAnchor, multiplier: 0.8),
            
            collectionView.topAnchor.constraint(equalTo: headerImageView.bottomAnchor, constant: 15),
            collectionView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 20),
            collectionView.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -20),
            collectionView.bottomAnchor.constraint(equalTo: bottomAnchor)
        ])
    }
}
