//
//  PokemonDetailProtocols.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 2/04/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Nishi
//

import Foundation

//MARK: Presenter -> Router
protocol PokemonDetailWireframeProtocol: AnyObject {
    
}

//MARK: View -> Presenter
protocol PokemonDetailPresenterProtocol: AnyObject {
    var interactor: PokemonDetailInteractorInputProtocol? { get set }
}

//MARK: Interactor -> Presenter
protocol PokemonDetailInteractorOutputProtocol: AnyObject {
    
}

//MARK: Presenter -> Interactor
protocol PokemonDetailInteractorInputProtocol: AnyObject {
    var presenter: PokemonDetailInteractorOutputProtocol?  { get set }
}

//MARK: Presenter -> View
protocol PokemonDetailViewProtocol: AnyObject {
    var presenter: PokemonDetailPresenterProtocol?  { get set }
}
