//
//  PokemonDetailViewController.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 2/04/25.
//  Template generated by Nishi
//

import UIKit

class PokemonDetailViewController: UIViewController {
	var presenter: PokemonDetailPresenterProtocol?
    
    /// Views for this controller
    let mainView = PokemonDetailView()

	override func viewDidLoad() {
        super.viewDidLoad()
        view = mainView
        
        setupGestures()
    }
    
    private func setupGestures() {
        
    }
}

extension PokemonDetailViewController: PokemonDetailViewProtocol {
    
}
