//
//  PokemonDetailPresenter.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 2/04/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Nishi
//

import UIKit

class PokemonDetailPresenter {
    weak private var view: PokemonDetailViewProtocol?
    var interactor: PokemonDetailInteractorInputProtocol?
    private let router: PokemonDetailWireframeProtocol

    init(interface: PokemonDetailViewProtocol, interactor: PokemonDetailInteractorInputProtocol?, router: PokemonDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension PokemonDetailPresenter: PokemonDetailPresenterProtocol {
    
}

extension PokemonDetailPresenter: PokemonDetailInteractorOutputProtocol {
    
}
