//
//  PokemonDetailView+Layout.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 2/04/25.
//  Template generated by Nishi
//

import UIKit

extension PokemonDetailView {
    func addViews() {
        
    }
    
    func setupConstraints() {
        NSLayoutConstraint.activate([
            
        ])
    }
}
