//
//  PokemonDetailInteractor.swift
//  PokedexBCI
//
//  Created Irwin Bravo Oporto on 2/04/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Nishi
//

import UIKit

class PokemonDetailInteractor: PokemonDetailInteractorInputProtocol {
    weak var presenter: PokemonDetailInteractorOutputProtocol?
}
